// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Views
{
    public partial class GetDataAddonDetails
    {
        public int AddonId { get; set; }
        public int AttributeId { get; set; }
        public int ValueId { get; set; }
        public bool Active { get; set; }
        public int? ProductId { get; set; }
        [StringLength(100)]
        public string AddonImage { get; set; }
        public string AddonDescription { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? AddonPrice { get; set; }
        public bool? AddonStatus { get; set; }
        public bool? AddonActive { get; set; }
        [StringLength(100)]
        public string ProductCode { get; set; }
        [StringLength(50)]
        public string AttibuteName { get; set; }
        public bool? AttributeActive { get; set; }
        [StringLength(50)]
        public string ValueName { get; set; }
        public bool? ValueActive { get; set; }
    }
}