// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Views
{
    public partial class GetDataAddonGroupPrice
    {
        public int? AddonId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        [Column("groupPriceID")]
        public int GroupPriceId { get; set; }
        [StringLength(100)]
        public string Attribute { get; set; }
        [StringLength(100)]
        public string AddonImage { get; set; }
        public bool? AddonStatus { get; set; }
        [StringLength(100)]
        public string ProductCode { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        [StringLength(10)]
        public string UnitCode { get; set; }
        [Required]
        public string AddonDescription { get; set; }
        public int? DomainId { get; set; }
        [Column("productTypeName")]
        [StringLength(50)]
        public string ProductTypeName { get; set; }
        public int? ProductId { get; set; }
    }
}