// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Views
{
    public partial class GetProductAndServices
    {
        public int ProductId { get; set; }
        [StringLength(100)]
        public string ProductCode { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductName { get; set; }
        public int ProductTypeId { get; set; }
        [Column("productTypeName")]
        [StringLength(50)]
        public string ProductTypeName { get; set; }
        public string ProductDescription { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProductPrice { get; set; }
        [StringLength(50)]
        public string ProductImage { get; set; }
        public int ProductUntiId { get; set; }
        public int? DomainId { get; set; }
        public bool ProductActive { get; set; }
        [Column("productStatusID")]
        public int? ProductStatusId { get; set; }
        [Column("productStatusName")]
        [StringLength(50)]
        public string ProductStatusName { get; set; }
    }
}