// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("attributeName", Schema = "productAndService")]
    public partial class AttributeName
    {
        [Key]
        [Column("attributeNameID")]
        public int AttributeNameId { get; set; }
        [Column("attributeNames")]
        [StringLength(100)]
        public string AttributeNames { get; set; }
        [Column("attributeNameActive")]
        public bool? AttributeNameActive { get; set; }
        [Column("domainID")]
        public int DomainId { get; set; }
        [Column("mainProductID")]
        public int MainProductId { get; set; }
    }
}