// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("attributeValue", Schema = "productAndService")]
    public partial class AttributeValue
    {
        [Key]
        [Column("attributeValueID")]
        public int AttributeValueId { get; set; }
        [Column("attributeValueName")]
        [StringLength(100)]
        public string AttributeValueName { get; set; }
        [Column("attributeNameID")]
        public int AttributeNameId { get; set; }
        [Column("attributeValueActive")]
        public bool? AttributeValueActive { get; set; }
    }
}