// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("attribute", Schema = "productAndService")]
    public partial class Attribute
    {
        [Key]
        [Column("attributeID")]
        public int AttributeId { get; set; }
        [Column("attributeName")]
        [StringLength(100)]
        public string AttributeName { get; set; }
        [Column("attributeValue")]
        [StringLength(200)]
        public string AttributeValue { get; set; }
        [Column("attributeAction")]
        public bool AttributeAction { get; set; }
        [Column("attributeActive")]
        public bool AttributeActive { get; set; }
    }
}