// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("bindGroupPrice", Schema = "productAndService")]
    public partial class BindGroupPrice
    {
        [Key]
        [Column("sellingPriceID")]
        public int SellingPriceId { get; set; }
        [Column("sellingPrice")]
        public int? SellingPrice { get; set; }
        [Column("productID")]
        public int ProductId { get; set; }
        [Column("groupPriceID")]
        public int GroupPriceId { get; set; }
    }
}