// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("bindAttribute", Schema = "productAndService")]
    public partial class BindAttribute
    {
        [Key]
        [Column("attributeID")]
        public int AttributeId { get; set; }
        [Column("productID")]
        public int ProductId { get; set; }
    }
}