// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("bindGroupPrice", Schema = "productAndService")]
    public partial class BindGroupPrice
    {
        [Key]
        [Column("bindGroupPriceID")]
        public int BindGroupPriceId { get; set; }
        [Column("groupPriceID")]
        public int GroupPriceId { get; set; }
        [Column("addonID")]
        public int AddonId { get; set; }
        [Column("domainId")]
        public int DomainId { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
    }
}