// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("groupPrice", Schema = "productAndService")]
    public partial class GroupPrice
    {
        [Key]
        [Column("groupPriceID")]
        public int GroupPriceId { get; set; }
        [Column("priceName")]
        [StringLength(100)]
        public string PriceName { get; set; }
        [Column("currencyCode")]
        public int CurrencyCode { get; set; }
        [Column("sellingPriceDefault")]
        public bool SellingPriceDefault { get; set; }
        [Column("domainID")]
        public int DomainId { get; set; }
        [Required]
        public bool? Active { get; set; }
    }
}