// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("productUnit", Schema = "productAndService")]
    public partial class ProductUnit
    {
        [Key]
        [Column("productUnitID")]
        public int ProductUnitId { get; set; }
        [StringLength(10)]
        public string UnitCode { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column("domainID")]
        public int DomainId { get; set; }
    }
}