// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("ProductAddonDetails", Schema = "productAndService")]
    public partial class ProductAddonDetails
    {
        [Key]
        public int AddonId { get; set; }
        [Key]
        public int AttributeId { get; set; }
        [Key]
        public int ValueId { get; set; }
        [Required]
        public bool? Active { get; set; }

        [ForeignKey(nameof(AddonId))]
        [InverseProperty(nameof(ProductAddons.ProductAddonDetails))]
        public virtual ProductAddons Addon { get; set; }
        [ForeignKey(nameof(AttributeId))]
        [InverseProperty(nameof(ProductAttributes.ProductAddonDetails))]
        public virtual ProductAttributes Attribute { get; set; }
    }
}