// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("ProductAttributes", Schema = "productAndService")]
    public partial class ProductAttributes
    {
        public ProductAttributes()
        {
            ProductAddonDetails = new HashSet<ProductAddonDetails>();
            ProductAttributeValues = new HashSet<ProductAttributeValues>();
        }

        [Key]
        public int AttributeId { get; set; }
        public int ProductId { get; set; }
        [Required]
        [StringLength(50)]
        public string AttibuteName { get; set; }
        [Required]
        public bool? AttributeActive { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty(nameof(Products.ProductAttributes))]
        public virtual Products Product { get; set; }
        [InverseProperty("Attribute")]
        public virtual ICollection<ProductAddonDetails> ProductAddonDetails { get; set; }
        [InverseProperty("Attribute")]
        public virtual ICollection<ProductAttributeValues> ProductAttributeValues { get; set; }
    }
}