// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("productAndAttirbute", Schema = "productAndService")]
    public partial class ProductAndAttirbute
    {
        [Key]
        [Column("productAndAttirbuteID")]
        public int ProductAndAttirbuteId { get; set; }
        [Column("mainProductID")]
        public int MainProductId { get; set; }
        [Column("attributeNameID")]
        public int AttributeNameId { get; set; }
        [Column("productSellInfo")]
        public int? ProductSellInfo { get; set; }
        [Column("productImageInAttirbute")]
        [StringLength(50)]
        public string ProductImageInAttirbute { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("action")]
        public bool Action { get; set; }
        [Column("active")]
        public bool Active { get; set; }
    }
}