// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("productStatus", Schema = "productAndService")]
    public partial class ProductStatus
    {
        [Key]
        [Column("productStatusID")]
        public int ProductStatusId { get; set; }
        [Column("productStatusName")]
        [StringLength(50)]
        public string ProductStatusName { get; set; }
    }
}